# -*- coding: utf-8 -*-
"""SpaCy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOh9WRdiF5zorf3UObWXjZ3ft86Jsybl
"""

# Install spaCy and download the English model
!pip install -U spacy
!python -m spacy download en_core_web_sm

import spacy
from google.colab import files
from IPython.core.display import display, HTML
from spacy import displacy

class TextAnalyzer:
    def __init__(self):

        uploaded = files.upload()
        self.file_name = next(iter(uploaded))
        with open(self.file_name, 'r') as f:
            self.text = f.read()

        self.nlp = spacy.load("en_core_web_sm")
        self.doc = self.nlp(self.text)

    def colored_entities(self):
        """Displays the text with named entities highlighted in color."""
        html = displacy.render(self.doc, style="ent")

        display(HTML(html))  # Displays in Colab with HTML rendering

    def entities(self, output_file="entities.txt"):
        entities = [(ent.text, ent.label_) for ent in self.doc.ents]
        with open(output_file, 'w') as f:
            for text, label in entities:
                line = f"{text} ({label})"
                print(line)
                f.write(line + "\n")

    def pos(self, output_file="pos_tags.txt"):
        with open(output_file, 'w') as f:
            for token in self.doc:
                line = f"{token.text}\t{token.pos_}"
                print(line)
                f.write(line + "\n")

#analyzer = TextAnalyzer()
#analyzer.colored_entities()
#analyzer.entities()
analyzer.pos(output_file="pos.txt")